# -*- coding: latin-1 -*-
# generated by wxGlade 0.4cvs on Wed Sep 28 23:29:23 2005

import wx
import serial

# begin wxGlade: dependencies
# end wxGlade

class ConfigSerial(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ConfigSerial.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizerFluxo_staticbox = wx.StaticBox(self, -1, "Controle de Fluxo")
        self.porta = wx.Choice(self, -1, choices=[])
        self.velocidade = wx.Choice(self, -1, choices=[])
        self.dados = wx.SpinCtrl(self, -1, "8", min=5, max=8, style=wx.SP_ARROW_KEYS|wx.TE_AUTO_URL)
        self.paridade = wx.Choice(self, -1, choices=["Nenhuma", u"Ímpar", "Par"])
        self.parada = wx.SpinCtrl(self, -1, "1", min=0, max=2, style=wx.SP_ARROW_KEYS|wx.TE_AUTO_URL)
        self.cfHardware = wx.CheckBox(self, -1, "RTS/CTS")
        self.cfSoftware = wx.CheckBox(self, -1, "Xon/Xoff")
        self.btCancelar = wx.Button(self, wx.ID_CANCEL, "")
        self.btOk = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        # Configurações da serial
        self.serial = kwds['serial']

        # Porta
        self.porta.Clear()
        for n in range(4):
            self.porta.Append(serial.device(n))
        self.porta.SetSelection(self.serial.port)

        # Baud
        self.velocidade.Clear()
        for n, baudrate in enumerate(self.serial.BAUDRATES):
            self.velocidade.Append(str(baudrate))
            if self.serial.baudrate == baudrate:
                self.velocidade.SetSelection(n)

        # Bits de Dados
        self.dados.SetValue (self.serial.bytesize);

        # Paridade
        self.paridade 

        # Bits de Parada
        self.parada.SetValue (self.serial.stopbits);

        # Controle de Fluxo
        self.cfHardware.SetValue (self.serial.rtscts);
        self.cfSoftware.SetValue (self.serial.xonxoff);

        

    def __set_properties(self):
        # begin wxGlade: ConfigSerial.__set_properties
        self.SetTitle(u"Configuração da Serial")
        self.porta.SetSelection(0)
        self.velocidade.SetSelection(0)
        self.paridade.SetSelection(0)
        self.btOk.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConfigSerial.__do_layout
        sizerJanela = wx.BoxSizer(wx.VERTICAL)
        sizerBotoes = wx.BoxSizer(wx.HORIZONTAL)
        sizerFluxo = wx.StaticBoxSizer(self.sizerFluxo_staticbox, wx.HORIZONTAL)
        sizerDados = wx.GridSizer(7, 2, 0, 0)
        label_1 = wx.StaticText(self, -1, "Porta:")
        sizerDados.Add(label_1, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.porta, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_2 = wx.StaticText(self, -1, "Velocidade:")
        sizerDados.Add(label_2, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.velocidade, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_3 = wx.StaticText(self, -1, "Bits de Dados:")
        sizerDados.Add(label_3, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.dados, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_4 = wx.StaticText(self, -1, "Paridade:")
        sizerDados.Add(label_4, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.paridade, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_5 = wx.StaticText(self, -1, "Bits de Parada:")
        sizerDados.Add(label_5, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.parada, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerJanela.Add(sizerDados, 1, wx.EXPAND, 0)
        sizerFluxo.Add(self.cfHardware, 0, wx.ALL, 3)
        sizerFluxo.Add(self.cfSoftware, 0, wx.ALL, 3)
        sizerJanela.Add(sizerFluxo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        linha = wx.StaticLine(self, -1)
        sizerJanela.Add(linha, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 3)
        sizerBotoes.Add(self.btCancelar, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        sizerBotoes.Add(self.btOk, 1, wx.ALL, 3)
        sizerJanela.Add(sizerBotoes, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        self.SetAutoLayout(True)
        self.SetSizer(sizerJanela)
        sizerJanela.Fit(self)
        sizerJanela.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class ConfigSerial


