# -*- coding: latin-1 -*-
# generated by wxGlade 0.4cvs on Wed Sep 28 23:29:23 2005

import wx

# begin wxGlade: dependencies
# end wxGlade

class ConfigSerial(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ConfigSerial.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.porta = wx.SpinCtrl(self, -1, "0", min=0, max=10, style=wx.SP_ARROW_KEYS|wx.TE_AUTO_URL)
        self.velocidade = wx.Choice(self, -1, choices=["1200", "2400", "4800", "9600", "19200", "38400", "57600", "115200"])
        self.bits = wx.SpinCtrl(self, -1, "8", min=7, max=9, style=wx.SP_ARROW_KEYS|wx.TE_AUTO_URL)
        self.paridade = wx.Choice(self, -1, choices=["Nenhuma", "Par", u"Ímpar"])
        self.stopBits = wx.SpinCtrl(self, -1, "1", min=0, max=2, style=wx.SP_ARROW_KEYS|wx.TE_AUTO_URL)
        self.btCancelar = wx.Button(self, wx.ID_CANCEL, "Cancelar")
        self.btOk = wx.Button(self, wx.ID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ConfigSerial.__set_properties
        self.SetTitle(u"Configuração da Serial")
        self.porta.SetToolTipString("0 = COM1:\n1 = COM2:\n...")
        self.velocidade.SetSelection(3)
        self.paridade.SetSelection(0)
        self.btOk.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConfigSerial.__do_layout
        sizerJanela = wx.BoxSizer(wx.VERTICAL)
        sizerBotoes = wx.BoxSizer(wx.HORIZONTAL)
        sizerDados = wx.GridSizer(7, 2, 0, 0)
        label_1 = wx.StaticText(self, -1, "Porta:")
        sizerDados.Add(label_1, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.porta, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_2 = wx.StaticText(self, -1, "Velocidade:")
        sizerDados.Add(label_2, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.velocidade, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_3 = wx.StaticText(self, -1, "Bits:")
        sizerDados.Add(label_3, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.bits, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_4 = wx.StaticText(self, -1, "Paridade:")
        sizerDados.Add(label_4, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.paridade, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        label_5 = wx.StaticText(self, -1, "Bit de Parada:")
        sizerDados.Add(label_5, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerDados.Add(self.stopBits, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        sizerJanela.Add(sizerDados, 1, wx.EXPAND, 0)
        linha = wx.StaticLine(self, -1)
        sizerJanela.Add(linha, 0, wx.EXPAND, 0)
        sizerBotoes.Add(self.btCancelar, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        sizerBotoes.Add(self.btOk, 1, wx.ALL, 3)
        sizerJanela.Add(sizerBotoes, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        self.SetAutoLayout(True)
        self.SetSizer(sizerJanela)
        sizerJanela.Fit(self)
        sizerJanela.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class ConfigSerial


