#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#Boa:App:BoaApp
# generated by wxGlade 0.4cvs on Thu Sep  1 12:48:30 2005

import wx
from JanelaPrincipal import JanelaPrincipal

modules ={u'janela': [1, u'Janela Principal', u'JanelaPrincipal.py'],
 u'tocador': [0, u'Tocador de áudio', u'tocador.py']}

class HandTalksApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        janela = JanelaPrincipal(None, -1, "")
        self.SetTopWindow(janela)
        janela.Show()
        return 1

# end of class HandTalksApp

if __name__ == "__main__":
    handtalks = HandTalksApp(0)
    handtalks.MainLoop()
