#!/usr/bin/env python
# -*- coding: latin-1 -*-
# generated by wxGlade 0.4cvs on Fri Sep 23 01:22:07 2005

import wx
from JanelaPrincipal import JanelaPrincipal

class HandTalksApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        janela = JanelaPrincipal(None, -1, "")
        self.SetTopWindow(janela)
        janela.Show()
        return 1

# end of class HandTalksApp

if __name__ == "__main__":
    handtalks = HandTalksApp(0)
    handtalks.MainLoop()
