#!/usr/bin/env python
# -*- coding: latin-1 -*-
# generated by wxGlade 0.4cvs on Fri Sep 23 01:22:07 2005

import wx
from HTMain import HTMain


class HTApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        main = HTMain(None, -1, "")
        self.SetTopWindow(main)
        main.Show()
        return 1

# end of class HTApp

if __name__ == "__main__":
    handtalks = HTApp(0)
    handtalks.MainLoop()
