#!/usr/bin/env python
# -*- coding: latin-1 -*-
# generated by wxGlade 0.4 on Sun Dec 11 04:46:16 2005

import wx
from HTMain import HTMain

class HTApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        main = HTMain(None, -1, "")
        self.SetTopWindow(main)
        main.Show()
        return 1

# end of class HTApp

