#!/usr/bin/env python
# -*- coding: latin-1 -*-
# generated by wxGlade 0.4 on Sun Dec 11 04:46:16 2005

import wx

# begin wxGlade: dependencies
# end wxGlade

class HTGloveWizard(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: HTGloveWizard.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.btCancelar = wx.Button(self, -1, "Cancelar")
        self.btVoltar = wx.Button(self, -1, "<< Anterior")
        self.btProximo = wx.Button(self, -1, u"Próximo >>")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btCancelarClick, self.btCancelar)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: HTGloveWizard.__set_properties
        self.SetTitle("dialog_1")
        self.btProximo.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: HTGloveWizard.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        botoes = wx.BoxSizer(wx.HORIZONTAL)
        conteudo = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(conteudo, 1, wx.EXPAND, 0)
        botoes.Add(self.btCancelar, 0, wx.ALL, 3)
        botoes.Add((20, 20), 0, wx.EXPAND, 0)
        botoes.Add(self.btVoltar, 0, wx.ALL, 3)
        botoes.Add(self.btProximo, 0, wx.ALL, 3)
        sizer_1.Add(botoes, 0, 0, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def btCancelarClick(self, event): # wxGlade: HTGloveWizard.<event_handler>
        print "Event handler `btCancelarClick' not implemented!"
        event.Skip()

# end of class HTGloveWizard


